# Generated by Django 2.2.28 on 2025-03-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankedifyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='listening_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
