# Generated by Django 2.2.28 on 2025-03-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankedifyapp', '0002_profile_listening_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningMinutesPerTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_minutes', models.CharField(max_length=100)),
                ('listening_minutes', models.IntegerField(default=0)),
                ('last_logged_in', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='username_profile',
            field=models.CharField(default='blank', max_length=100),
        ),
    ]
