# Generated by Django 2.2.28 on 2025-03-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankedifyapp', '0003_auto_20250327_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username_profile',
        ),
    ]
