# Generated by Django 2.2.28 on 2025-03-27 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankedifyapp', '0005_auto_20250327_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningminutespertime',
            name='username_minutes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
