# Generated by Django 2.2.28 on 2025-03-28 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankedifyapp', '0007_auto_20250327_2342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
